<a href="https://colab.research.google.com/github/YvTur/violencia_genero_mty/blob/main/Violencia_de_genero_911_Monterrey%2C_Mexico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Datos de 911 sobre la violencia de genero en Monterrey

Estos datos fueron extraidos del portal de datos abiertos del municipio de Monterrey, Nuevo Leon, Mexico. 

El objetivo es usarlos como ejercicio para el manejo de librerias relacionadas con ciencia de datos.

Anexo el link de referencía: https://datos.monterrey.gob.mx/dataset/reportes-al-911-por-violencia-de-genero

Nota: Habra combinación de idiomas en las notas.

##Data General

In [32]:
#We first call the pandas library
import pandas as pd

#Note for future Yves, when calling a csv on colab, 
#call it from github and call the raw material

url="https://raw.githubusercontent.com/YvTur/violencia_genero_mty/main/violencia_mty.csv"

#We call the url of the CSV
df =pd.read_csv(url)
df

,numero_reporte,fecha,municipio,colonia,estado,descripcion_tipo,corporacion,hora_recepcion,descripcion_cierre,latitud,longitud,via_recepcion
0,170000290,1/1/2017,Monterrey,San bernabe 9 fom 112,NL,Violencia familiar,FZACIVIL,0:20:24,Falsa alarma,25.766637,-100.371554,Telefono
1,170000476,1/1/2017,Monterrey,Independencia,NL,Violencia familiar,FZACIVIL,0:34:01,Falsa alarma,25.658518,-100.331530,Telefono
2,170000494,1/1/2017,Monterrey,Gloria mendiola,NL,Violencia familiar,FZACIVIL,0:35:24,Hecho real,25.772323,-100.359753,Telefono
3,170000558,1/1/2017,Monterrey,Independencia,NL,Violencia familiar,FZACIVIL,0:39:58,No especificado,25.658936,-100.330733,Telefono
4,170000567,1/1/2017,Monterrey,Independencia,NL,Violencia de pareja,FZACIVIL,0:40:22,Falsa alarma,25.657930,-100.325391,Telefono
...,...,...,...,...,...,...,...,...,...,...,...,...
137035,223233177,30/09/22,Monterrey,Condocasa mitras,NL,Violencia de pareja,FZACIVIL,23:52:59,Hecho real,25.728052,-100.356052,Telefono
137036,223233186,30/09/22,Monterrey,Condocasa mitras,NL,Violencia de pareja,FZACIVIL,23:53:42,No especificado,25.727870,-100.355614,Telefono
137037,223233189,30/09/22,Monterrey,El porvenir,NL,Violencia familiar,FZACIVIL,23:53:54,No especificado,25.767785,-100.368310,Telefono
137038,223233205,30/09/22,Monterrey,San bernabe 3 fom 121,NL,Violencia familiar,FZACIVIL,23:55:58,No especificado,25.756340,-100.371249,Telefono
137039,223233232,30/09/22,Monterrey,San bernabe 3 fom 121,NL,Violencia familiar,FZACIVIL,23:59:42,No especificado,25.757628,-100.370917,Telefono

In [33]:
#Pandas use the loc attribute to return one or more specified row(s)
#refer to the row index:
#Te da el nombre de el nombre de las columnas y la primera fila

df.loc[0]

numero_reporte                    170000290
fecha                              1/1/2017
municipio                         Monterrey
colonia               San bernabe 9 fom 112
estado                                   NL
descripcion_tipo         Violencia familiar
corporacion                        FZACIVIL
hora_recepcion                      0:20:24
descripcion_cierre             Falsa alarma
latitud                           25.766637
longitud                        -100.371554
via_recepcion                      Telefono
Name: 0, dtype: object

In [34]:
#El siguiente codigo te da las dos primeras filas
df.loc[[0,0]]

,numero_reporte,fecha,municipio,colonia,estado,descripcion_tipo,corporacion,hora_recepcion,descripcion_cierre,latitud,longitud,via_recepcion
0,170000290,1/1/2017,Monterrey,San bernabe 9 fom 112,NL,Violencia familiar,FZACIVIL,0:20:24,Falsa alarma,25.766637,-100.371554,Telefono
0,170000290,1/1/2017,Monterrey,San bernabe 9 fom 112,NL,Violencia familiar,FZACIVIL,0:20:24,Falsa alarma,25.766637,-100.371554,Telefono

In [35]:
#imprimes la cantidad deseada de filas de la parte de arriba. 
df.head(5)

,numero_reporte,fecha,municipio,colonia,estado,descripcion_tipo,corporacion,hora_recepcion,descripcion_cierre,latitud,longitud,via_recepcion
0,170000290,1/1/2017,Monterrey,San bernabe 9 fom 112,NL,Violencia familiar,FZACIVIL,0:20:24,Falsa alarma,25.766637,-100.371554,Telefono
1,170000476,1/1/2017,Monterrey,Independencia,NL,Violencia familiar,FZACIVIL,0:34:01,Falsa alarma,25.658518,-100.331530,Telefono
2,170000494,1/1/2017,Monterrey,Gloria mendiola,NL,Violencia familiar,FZACIVIL,0:35:24,Hecho real,25.772323,-100.359753,Telefono
3,170000558,1/1/2017,Monterrey,Independencia,NL,Violencia familiar,FZACIVIL,0:39:58,No especificado,25.658936,-100.330733,Telefono
4,170000567,1/1/2017,Monterrey,Independencia,NL,Violencia de pareja,FZACIVIL,0:40:22,Falsa alarma,25.657930,-100.325391,Telefono

In [36]:
#La funcion para mandar hablarle  al final de las filas
df.tail(5)

,numero_reporte,fecha,municipio,colonia,estado,descripcion_tipo,corporacion,hora_recepcion,descripcion_cierre,latitud,longitud,via_recepcion
137035,223233177,30/09/22,Monterrey,Condocasa mitras,NL,Violencia de pareja,FZACIVIL,23:52:59,Hecho real,25.728052,-100.356052,Telefono
137036,223233186,30/09/22,Monterrey,Condocasa mitras,NL,Violencia de pareja,FZACIVIL,23:53:42,No especificado,25.727870,-100.355614,Telefono
137037,223233189,30/09/22,Monterrey,El porvenir,NL,Violencia familiar,FZACIVIL,23:53:54,No especificado,25.767785,-100.368310,Telefono
137038,223233205,30/09/22,Monterrey,San bernabe 3 fom 121,NL,Violencia familiar,FZACIVIL,23:55:58,No especificado,25.756340,-100.371249,Telefono
137039,223233232,30/09/22,Monterrey,San bernabe 3 fom 121,NL,Violencia familiar,FZACIVIL,23:59:42,No especificado,25.757628,-100.370917,Telefono

In [37]:
#el siguiente metodo de pandas, sirve apra ver el tipo de objeto que se maneja en nuestras columnas o atributos.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137040 entries, 0 to 137039
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   numero_reporte      137040 non-null  int64
 1   fecha               137040 non-null  object
 2   municipio           137040 non-null  object
 3   colonia             137009 non-null  object
 4   estado              136990 non-null  object
 5   descripcion_tipo    137040 non-null  object
 6   corporacion         137040 non-null  object
 7   hora_recepcion      137040 non-null  object
 8   descripcion_cierre  137040 non-null  object
 9   latitud             137040 non-null  float64
 10  longitud            137040 non-null  float64
 11  via_recepcion       137040 non-null  object
dtypes: float64(2), int64(1), object(9)
memory usage: 12.5+ MB

##Data Cleaning

**¿Qué es el data cleaning?**


Datos malos podrian ser traducidos en:
*  celdas vacias
*  Datos en un formato inadecuado
*  Datos erroneos
*   Duplicados

###Replace using empty values

In [20]:
#La funcion fillna() mete un valor especifico en los espacios vacios
df.fillna(130, inplace = True)
#Puedes meter en una columna especifica el valor que desees
df["estado"].fillna(130, inplace=True)

In [21]:
df

,numero_reporte,fecha,municipio,colonia,estado,descripcion_tipo,corporacion,hora_recepcion,descripcion_cierre,latitud,longitud,via_recepcion
0,170000290,1/1/2017,Monterrey,San bernabe 9 fom 112,NL,Violencia familiar,FZACIVIL,0:20:24,Falsa alarma,25.766637,-100.371554,Telefono
1,170000476,1/1/2017,Monterrey,Independencia,NL,Violencia familiar,FZACIVIL,0:34:01,Falsa alarma,25.658518,-100.331530,Telefono
2,170000494,1/1/2017,Monterrey,Gloria mendiola,NL,Violencia familiar,FZACIVIL,0:35:24,Hecho real,25.772323,-100.359753,Telefono
3,170000558,1/1/2017,Monterrey,Independencia,NL,Violencia familiar,FZACIVIL,0:39:58,No especificado,25.658936,-100.330733,Telefono
4,170000567,1/1/2017,Monterrey,Independencia,NL,Violencia de pareja,FZACIVIL,0:40:22,Falsa alarma,25.657930,-100.325391,Telefono
...,...,...,...,...,...,...,...,...,...,...,...,...
137035,223233177,30/09/22,Monterrey,Condocasa mitras,NL,Violencia de pareja,FZACIVIL,23:52:59,Hecho real,25.728052,-100.356052,Telefono
137036,223233186,30/09/22,Monterrey,Condocasa mitras,NL,Violencia de pareja,FZACIVIL,23:53:42,No especificado,25.727870,-100.355614,Telefono
137037,223233189,30/09/22,Monterrey,El porvenir,NL,Violencia familiar,FZACIVIL,23:53:54,No especificado,25.767785,-100.368310,Telefono
137038,223233205,30/09/22,Monterrey,San bernabe 3 fom 121,NL,Violencia familiar,FZACIVIL,23:55:58,No especificado,25.756340,-100.371249,Telefono
137039,223233232,30/09/22,Monterrey,San bernabe 3 fom 121,NL,Violencia familiar,FZACIVIL,23:59:42,No especificado,25.757628,-100.370917,Telefono

### Replace using mean, median or mode

In [28]:
#We are going to explore ways to extract different stastitics from a column

x = df["latitud"].mean()
y = df["latitud"].median()
z = df["latitud"].mode()[0]
print(x,y,z)
#En esta parte puedes reemplazar el valor de alguna parte vacia por el promedio o mediana o moda
# df["latitud"].fillna(x, inplace = True)

25.698428830086108 25.7312315 25.731789

###Removing Rows

In [29]:
#Puedes remover alguna fila que tenga elementos nulos con el siguiente comando. En este caso nuestro data set tiene elemenos nulos en el apartado de estado. Lo cual es facil sustituir
#df.dropna(subset=['fecha'], inplace = True)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137040 entries, 0 to 137039
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   numero_reporte      137040 non-null  int64
 1   fecha               137040 non-null  object
 2   municipio           137040 non-null  object
 3   colonia             137040 non-null  object
 4   estado              137040 non-null  object
 5   descripcion_tipo    137040 non-null  object
 6   corporacion         137040 non-null  object
 7   hora_recepcion      137040 non-null  object
 8   descripcion_cierre  137040 non-null  object
 9   latitud             137040 non-null  float64
 10  longitud            137040 non-null  float64
 11  via_recepcion       137040 non-null  object
dtypes: float64(2), int64(1), object(9)
memory usage: 12.5+ MB